export const MATCH_NOT_STARTED = "MATCH_NOT_STARTED";
export const MATCH_IN_SONG_SELECTION = "MATCH_IN_SONG_SELECTION";
export const MATCH_IN_SCORE_ENTRY = "MATCH_IN_SCORE_ENTRY";
export const MATCH_SCORED = "MATCH_SCORED";
